# Generated by Django 5.0.4 on 2024-04-22 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groapp', '0002_colorvariant_quantityvariant_sizevariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groapp.product')),
            ],
        ),
    ]
