# Generated by Django 5.0.4 on 2024-04-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groapp', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
