# Generated by Django 5.0.4 on 2024-04-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groapp', '0006_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Name',
            new_name='name',
        ),
    ]
