# Generated by Django 5.0.4 on 2024-05-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groapp', '0007_rename_name_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
