# Generated by Django 5.0.4 on 2024-05-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groapp', '0012_status_send_feedback_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Send_Feedback',
        ),
    ]
