# Generated by Django 5.0.4 on 2024-05-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groapp', '0014_remove_cart_profile_cart_quantity_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
