# Generated by Django 5.0.4 on 2024-05-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groapp', '0015_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
