# Generated by Django 5.0.2 on 2024-03-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='title',
            new_name='bio',
        ),
    ]
